name: Testing

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: ~

jobs:

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        id: toolchain
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ steps.toolchain.outputs.cachekey }}
      - run: cargo clippy -- --deny warnings
      - run: cargo test --all-features
