name: Testing

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: ~

env:
  CARGO_TERM_COLOR: always

jobs:

  unit:
    name: Testing using Rust ${{ matrix.toolchain }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        toolchain:
          - 1.74   # Ensure MSRV is true.
          - stable # Ensure latest support.
    steps:
      - uses: actions/checkout@v4
      - id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          components: clippy,rustfmt
          toolchain: ${{ matrix.toolchain }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ steps.toolchain.outputs.cachekey }}
      - run: cargo fmt -- --check
      - run: cargo clippy -- --deny warnings
      - run: cargo test --all-features
